spring.application.name=space-shell-gateway

spring.datasource.url =  jdbc:postgresql://localhost:5432/SpaceShellDB
spring.datasource.username = postgres
spring.datasource.password = postgres

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect